# Generated by Django 3.1.2 on 2020-10-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='YWC', max_length=200)),
                ('caption', models.TextField(default='you were chosen', max_length=500)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
