# Generated by Django 3.1.2 on 2020-10-22 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ywc art', max_length=200)),
                ('artist', models.CharField(default='annonymous', max_length=400)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
