# Generated by Django 3.1.2 on 2020-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='caption',
            field=models.TextField(default='You Were Chosen is a new line of thought.\n\n                               A line of thought to make people believe in their dreams, make people take authority of themselves and make a diverse and creative future.\n\n                               Most importantly, to build a society that can learn to love each other, a society to feel that their lives have meaning, a society to feel that they are important.'),
        ),
    ]
